# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[subnavigation]]
  name = "About"
  pageRef = "About"
  weight = 5

[[subnavigation]]
  name = "Garden Review"
  pageRef = "garden review"
  weight = 10

[[main]]
  name = "Personal"
  weight = 10

[[main]]
  name = "Musings"
  pageRef = "musings"
  parent = "Personal"

[[main]]
  name = "Projects"
  weight = 15
  pageRef = "Project"

[[main]]
  name = "Moments"
  pageRef = "moments"
  parent = "Personal"

[[main]]
  name = "Knowledge Base"
  weight = 25

[[main]]
  name = "Ideas"
  parent = "Projects"
  pageRef = "ideas"
  weight = 30

[[main]]
  name = "Finished"
  parent = "Projects"
  pageRef = "finished projects"
  weight = 10

[[main]]
  name = "In Progress"
  parent = "Projects"
  pageRef = "In Progress"
  weight = 20

[[main]]
  name = "Never-ending"
  parent = "Projects"
  pageRef = "Never-ending"
  weight = 40

[[main]]
  name = "Ads"
  pageRef = "ads"
  parent = "Sources"

[[main]]
  name = "Animation"
  pageRef = "animation"
  parent = "Sources"

[[main]]
  name = "Tutorials"
  pageRef = "tutorials"
  parent = "Knowledge Base"

[[main]]
  name = "WIKA"
  pageRef = "WIKA"
  parent = "Knowledge Base"

[[main]]
  name = "Tools"
  pageRef = "tools"
  parent = "Knowledge Base"

[[main]]
  name = "Concepts"
  pageRef = "concepts"
  parent = "Knowledge Base"

[[main]]
  name = "Comparisons"
  pageRef = "Comparisons"
  parent = "Knowledge Base"

[[main]]
  name = "Creatures"
  pageRef = "creatures"
  parent = "Knowledge Base"

[[main]]
  name = "Experiments"
  pageRef = "experiments"
  parent = "Knowledge Base"

[[main]]
  name = "Notions"
  pageRef = "notion"
  parent = "Knowledge Base"

[[main]]
  name = "Places"
  pageRef = "Places"
  parent = "Knowledge Base"

[[main]]
  name = "Techniques"
  pageRef = "Techniques"
  parent = "Knowledge Base"

[[main]]
  name = "Sources"
  pageRef = "source"
  weight = 20

[[main]]
  name = "Memes"
  pageRef = "Memes"
  parent = "Sources"

[[main]]
  name = "Blog Posts"
  pageRef = "blog post"
  parent = "Sources"

[[main]]
  name = "Books"
  pageRef = "books"
  parent = "Sources"

[[main]]
  name = "Comic Books"
  pageRef = "comic books"
  parent = "Sources"

[[main]]
  name = "Collections"
  pageRef = "collections"
  parent = "Sources"

[[main]]
  name = "Discussions"
  pageRef = "discussions"
  parent = "Sources"

[[main]]
  name = "Encyclopedia Articles"
  pageRef = "ency"
  parent = "Sources"

[[main]]
  name = "Fanworks"
  pageRef = "fanwork"
  parent = "Sources"

[[main]]
  name = "Fanfics"
  pageRef = "fanfic"
  parent = "Fanworks"

[[main]]
  name = "Online Courses"
  pageRef = "mooc"
  parent = "Sources"

[[main]]
  name = "Podcasts"
  pageRef = "podcast"
  parent = "Sources"

[[main]]
  name = "Scholarly Articles"
  pageRef = "scholarly article"
  parent = "Sources"

[[main]]
  name = "Videos"
  pageRef = "video"
  parent = "Sources"

[[main]]
  name = "Videogames"
  pageRef = "videogame"
  parent = "Sources"

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[subnavigation]]
  name = "Tags"
  pageRef = "tags"
  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
