# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  weight = 5

[[main]]
  name = "Projects"
  weight = 30

[[main]]
  name = "Knowledge Base"
  weight = 25

[[main]]
  name = "Ideas"
  parent = "Projects"
  pageRef = "ideas"
  weight = 30

[[main]]
  name = "Finished"
  parent = "Projects"
  pageRef = "proj_fin"
  weight = 10

[[main]]
  name = "In Progress"
  parent = "Projects"
  pageRef = "In Progress"
  weight = 20

[[main]]
  name = "Moments"
  pageRef = "moments"

[[main]]
  name = "Writing"
  weight = 10
[[main]]
  name = "Tutorials"
  pageRef = "tutorials"
  parent = "Knowledge Base"

[[main]]
  name = "WIKA"
  pageRef = "WIKA"
  parent = "Knowledge Base"

[[main]]
  name = "Tools"
  pageRef = "tools"
  parent = "Knowledge Base"

[[main]]
  name = "Concepts"
  pageRef = "concepts"
  parent = "Knowledge Base"

[[main]]
  name = "Notions"
  pageRef = "notion"
  parent = "Knowledge Base"

[[main]]
  name = "Sources"
  pageRef = "source"
  weight = 20

[[main]]
  name = "Anime"
  pageRef = "anime"
  parent = "Sources"

[[main]]
  name = "Blog Posts"
  pageRef = "blog_post"
  parent = "Sources"

[[main]]
  name = "Books"
  pageRef = "books"
  parent = "Sources"

[[main]]
  name = "Comic Books"
  pageRef = "comic_book"
  parent = "Sources"

[[main]]
  name = "Collections"
  pageRef = "collection"
  parent = "Sources"

[[main]]
  name = "Encyclopedia Articles"
  pageRef = "ency"
  parent = "Sources"

[[main]]
  name = "Fanworks"
  pageRef = "fanwork"
  parent = "Sources"

[[main]]
  name = "Fanfics"
  pageRef = "fanfic"
  parent = "Fanworks"

[[main]]
  name = "Music"
  pageRef = "music"
  parent = "Sources"

[[main]]
  name = "Online Courses"
  pageRef = "mooc"
  parent = "Sources"

[[main]]
  name = "Podcasts"
  pageRef = "podcast"
  parent = "Sources"

[[main]]
  name = "Videos"
  pageRef = "video"
  parent = "Sources"

[[main]]
  name = "Videogames"
  pageRef = "videogame"
  parent = "Sources"

[[main]]
  name = "Western Animation"
  pageRef = "w_cartoons"
  parent = "Sources"

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
