[module]
[module.hugoVersion]
extended = true
min = "0.141.0"
max = "0.150.0"

# IndieWeb authorization endpoints


[Params.indieweb]
  authorizationEndpoint = "https://indieauth.com/auth"
  tokenEndpoint = "https://tokens.indieauth.com/token"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

